### PR TITLE
Added basic email support .

### PR DESCRIPTION
**Pull request by born-2learn**
Used **smtplib** for now . **email.MIME** is on the way. An _email is successfully sent_ when motion is detected.
The email has been allowed access from less secure apps.

### CODE REVIEW

**Comment by NIteshx2** [comment]
Conflicts. Update your code and then again implement this feature in windows.py

**Comment by born-2learn** [comment]
I'll look into it after my exams, is that ok?

**Comment by born-2learn** [comment]
Resolved conflict

**Comment by NIteshx2** [comment]
It looks good, just wait till 14 dec and we'll merge it into our code.

**Comment by NIteshx2** [comment]
you also need to send a working video or gif of successful testing.

**Comment by born-2learn** [comment]
Will surely add it, anyways PR will be merged by 14th.

**Pull request closed without merging**
