### PR TITLE
Added timer initialisation on the video frames

### PR DESCRIPTION
**Pull request by johri002**
Show video frames while the code starts with the timer to get an idea of what base background image is set as.
Solved issue #17

### CODE REVIEW

**Comment by NIteshx2** [comment]
Great ! Also , Because of my final exams , I won't be able to test. So please test and send me a Screenshot on mail or on the gitter channel. Also , it would be great if you joined our gitter channel.

**Comment by NIteshx2** [comment]
I'll edit the reset mechanism Myself . I was expecting that you would fix that. Merging for writing on output itself

**Comment by johri002** [comment]
Don't worry! I have thoroughly checked and tested all the PR I am sending. Also, I will update you with the working shots for the same.

**Comment by johri002** [comment]
I am working on it.

**Pull request merged**
